---

# dnf installs

- name: upgrade all packages
  dnf:
    name: "*"
    state: latest

- name: install chromium
  dnf:
    name: chromium
    state: present

- name: install keepassxc
  dnf:
    name: keepassxc
    state: present

# flatpack installs

- name: install evolution from flathub
  flatpak:
    name: org.gnome.Evolution
    state: present